// examples/next/app/page.tsx
import { TegakiRenderer } from 'tegaki';
import bundle from 'tegaki/fonts/caveat';
import { ScrubDemo } from './demo';

export default function Home() {
  return (
    <main className="page">
      <h1>Tegaki × Next.js</h1>
      <p>
        Next.js App Router app using the <code>tegaki</code> React adapter. In Next.js 16 <strong>Turbopack is the default bundler</strong>{' '}
        for both <code>next dev</code> and <code>next build</code>, so this page exercises Tegaki under Turbopack.
      </p>

      <section>
        <h2>Looping</h2>
        <TegakiRenderer font={bundle} time={{ mode: 'uncontrolled', speed: 1, loop: true, loopGap: 1 }} style={{ fontSize: '64px' }}>
          Hello, Next.js!
        </TegakiRenderer>
      </section>

      <section>
        <h2>Scrubbable (client state)</h2>
        <ScrubDemo />
      </section>

      <section>
        <h2>With plugins (by name)</h2>
        <TegakiRenderer
          font={bundle}
          time={{ mode: 'uncontrolled', speed: 1, loop: true, loopGap: 1 }}
          plugins={['strokeGradient', ['glow', { radius: 0.1, color: '#00ccff' }]]}
          style={{ fontSize: '56px' }}
        >
          Fancy!
        </TegakiRenderer>
      </section>
    </main>
  );
}

// examples/svelte/src/App.svelte
<script lang="ts">
import bundle from 'tegaki/fonts/caveat';
import { TegakiRenderer } from 'tegaki/svelte';

let time = $state(8);
</script>

<main class="page">
  <h1>Tegaki × Svelte</h1>
  <p>Vite + Svelte 5 app using the <code>tegaki/svelte</code> adapter.</p>

  <section id="looping">
    <h2>Looping</h2>
    <TegakiRenderer font={bundle} text="Hello, Svelte!" time={{ mode: 'uncontrolled', speed: 1, loop: true, loopGap: 1 }} style="font-size: 64px" />
  </section>

  <section id="scrubbable">
    <h2>Scrubbable</h2>
    <input type="range" min={0} max={8} step={0.01} bind:value={time} />
    <TegakiRenderer font={bundle} text="Scrub me!" {time} style="font-size: 48px" />
  </section>
</main>
