// packages/renderer/src/react/TegakiRenderer.tsx
'use client';

import {
  type ComponentPropsWithoutRef,
  createElement,
  type ElementType,
  type ReactNode,
  type Ref,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import { TegakiEngine } from '../core/engine.ts';
import type { TegakiEngineOptions } from '../core/types.ts';
import type { Coercible } from '../lib/utils.ts';
import { coerceToString } from '../lib/utils.ts';
import type { TegakiEffects } from '../types.ts';

/** Imperative handle exposed via the `ref` prop. */
export interface TegakiRendererHandle {
  /** The underlying engine instance. `null` before mount and after unmount. */
  readonly engine: TegakiEngine | null;
  /** The container DOM element. */
  readonly element: HTMLElement | null;
}

interface TegakiRendererBaseProps<E extends TegakiEffects<E> = Record<string, never>> extends Omit<TegakiEngineOptions, 'effects'> {
  /** Imperative handle ref for playback controls and DOM access. */
  ref?: Ref<TegakiRendererHandle>;

  /** Children coerced to string. Strings and numbers are kept; everything else is ignored. */
  children?: Coercible;

  /** Visual effects applied during canvas rendering. */
  effects?: E;

  /** When true, the rendered text is editable via contentEditable. */
  editable?: boolean;

  /** Called when the user edits the text (only when `editable` is true). */
  onTextChange?: (text: string) => void;
}

export type TegakiRendererProps<C extends ElementType = 'div', E extends TegakiEffects<E> = Record<string, never>> = {
  as?: C;
} & TegakiRendererBaseProps<E> &
  Omit<ComponentPropsWithoutRef<C>, keyof TegakiRendererBaseProps<Record<string, never>> | 'as'>;

function reactCreateElement(tag: string, props: Record<string, any>, ...children: (ReactNode | string)[]): ReactNode {
  return createElement(tag, { ...props, key: props['data-tegaki'] }, ...children);
}

export function TegakiRenderer<const C extends ElementType = 'div', const E extends TegakiEffects<E> = Record<string, never>>(
  props: TegakiRendererProps<C, E>,
) {
  const {
    as: Tag = 'div' as ElementType,
    ref,
    font,
    text,
    children,
    time: timeProp,
    onComplete,
    onChangeTimeline,
    effects,
    quality,
    timing,
    showOverlay,
    direction,
    shaper,
    sound,
    editable,
    onTextChange,
    ...elementProps
  } = props as TegakiRendererProps<ElementType, E>;

  const containerRef = useRef<HTMLElement>(null);
  const engineRef = useRef<TegakiEngine | null>(null);
  const resolvedText = text ?? coerceToString(children);

  // --- Editable: internal text state that resets when controlled text changes ---
  const [internalText, setInternalText] = useState(resolvedText);
  const [prevResolvedText, setPrevResolvedText] = useState(resolvedText);
  if (prevResolvedText !== resolvedText) {
    setPrevResolvedText(resolvedText);
    setInternalText(resolvedText);
  }

  const displayText = editable ? internalText : resolvedText;

  // Render the element tree via the engine's static method (SSR-safe)
  const engineOptions: TegakiEngineOptions = {
    text: displayText,
    font,
    time: timeProp,
    effects: effects as Record<string, any>,
    quality,
    timing,
    showOverlay,
    direction,
    shaper,
    sound,
    onComplete,
    onChangeTimeline,
  };
  const { rootProps, content } = TegakiEngine.renderElements(engineOptions, reactCreateElement);
  const { style: rootStyle, ...rootAttrs } = rootProps;

  // Create engine on mount, adopting the pre-rendered elements
  useEffect(() => {
    const engine = new TegakiEngine(containerRef.current!, { adopt: true });
    engineRef.current = engine;
    return () => {
      engine.destroy();
      engineRef.current = null;
    };
  }, []);

  // Update engine with current props every render
  useEffect(() => {
    engineRef.current?.update(engineOptions);
  });

  // --- Editable: contentEditable + input handling ---
  const onTextChangeRef = useRef(onTextChange);
  onTextChangeRef.current = onTextChange;

  useEffect(() => {
    if (!editable) return;
    const container = containerRef.current;
    if (!container) return;
    const overlay = container.querySelector<HTMLElement>('[data-tegaki="overlay"]');
    if (!overlay) return;

    overlay.contentEditable = 'plaintext-only';
    overlay.style.caretColor = 'auto';

    const handleInput = () => {
      const newText = overlay.textContent ?? '';
      setInternalText(newText);
      onTextChangeRef.current?.(newText);
    };

    overlay.addEventListener('input', handleInput);
    return () => {
      overlay.removeEventListener('input', handleInput);
      overlay.contentEditable = 'inherit';
      overlay.style.caretColor = '';
    };
  }, [editable]);

  // Imperative handle
  useImperativeHandle(
    ref,
    () => ({
      get engine() {
        return engineRef.current;
      },
      get element() {
        return containerRef.current;
      },
    }),
    [],
  );

  // Merge engine root styles with user-provided styles
  const mergedStyle = { ...rootStyle, ...elementProps.style };

  return createElement(Tag, { ...rootAttrs, ...elementProps, ref: containerRef, style: mergedStyle } as any, content);
}

// packages/renderer/src/solid/TegakiRenderer.tsx
/** @jsxImportSource solid-js */
import { createEffect, createMemo, type JSX, on, onCleanup, onMount, splitProps } from 'solid-js';
import { TegakiEngine } from '../core/engine.ts';
import type { TegakiEngineOptions } from '../core/types.ts';
import type { TegakiEffects } from '../types.ts';

export interface TegakiRendererProps extends Omit<TegakiEngineOptions, 'effects'> {
  /** Visual effects applied during canvas rendering. */
  effects?: TegakiEffects<Record<string, any>>;
  class?: string;
  ref?: (handle: TegakiRendererHandle) => void;
  [key: string]: any;
}

export interface TegakiRendererHandle {
  readonly engine: TegakiEngine | null;
  readonly element: HTMLDivElement | null;
}

function solidCreateElement(tag: string, props: Record<string, any>, ...children: (JSX.Element | string)[]): JSX.Element {
  const parts: string[] = [];
  for (const [key, value] of Object.entries(props)) {
    if (value == null || value === false) continue;
    if (key === 'style' && typeof value === 'object') {
      const css = Object.entries(value)
        .filter(([, v]) => v != null)
        .map(([k, v]) => {
          const prop = k.startsWith('--') ? k : k.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
          const val = typeof v === 'number' && !k.startsWith('--') ? `${v}px` : String(v);
          return `${prop}:${val}`;
        })
        .join(';');
      if (css) parts.push(`style="${escapeAttr(css)}"`);
    } else if (typeof value === 'boolean') {
      parts.push(key);
    } else {
      parts.push(`${key}="${escapeAttr(String(value))}"`);
    }
  }
  const open = parts.length > 0 ? `<${tag} ${parts.join(' ')}>` : `<${tag}>`;
  const content = children.map((c) => (typeof c === 'string' && !c.startsWith('<') ? escapeHtml(c) : (c as string))).join('');
  return `${open}${content}</${tag}>` as unknown as JSX.Element;
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function TegakiRenderer(props: TegakiRendererProps) {
  const [local, divProps] = splitProps(props, [
    'text',
    'font',
    'time',
    'onComplete',
    'onChangeTimeline',
    'effects',
    'quality',
    'timing',
    'showOverlay',
    'direction',
    'shaper',
    'sound',
    'ref',
  ]);

  let container!: HTMLDivElement;
  let engine: TegakiEngine | null = null;

  const engineOptions = createMemo<TegakiEngineOptions>(() => ({
    text: local.text,
    font: local.font,
    time: local.time,
    effects: local.effects as Record<string, any>,
    quality: local.quality,
    timing: local.timing,
    showOverlay: local.showOverlay,
    direction: local.direction,
    shaper: local.shaper,
    sound: local.sound,
    onComplete: local.onComplete,
    onChangeTimeline: local.onChangeTimeline,
  }));

  // Compute initial HTML once — after the engine adopts, all updates go through engine.update().
  const { rootProps, content } = TegakiEngine.renderElements(engineOptions(), solidCreateElement);
  const innerHTML = content as unknown as string;

  onMount(() => {
    engine = new TegakiEngine(container, { ...engineOptions(), adopt: true });
    local.ref?.({ engine, element: container });
  });

  onCleanup(() => {
    engine?.destroy();
    engine = null;
  });

  createEffect(
    on(engineOptions, (options) => {
      engine?.update(options);
    }),
  );

  const mergedStyle = { ...rootProps.style, ...(typeof divProps.style === 'object' ? divProps.style : {}) };

  return <div ref={container!} data-tegaki="root" dir="auto" {...divProps} style={mergedStyle} innerHTML={innerHTML} />;
}
